spring:
  sql:
    init:
      mode: never
  jpa:
    show-sql: true
    properties:
      format_sql: true
    defer-datasource-initialization: true
  datasource:
    #    url: jdbc:h2:mem:testdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ktcloud?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: zz0722zz0722!
#  h2:
#    console:
#      enabled: true
